services:
  - type: web
    name: ptm_recon_agent
    env: node
    buildCommand: |
      PLAYWRIGHT_BROWSERS_PATH=0 npm install
      PLAYWRIGHT_BROWSERS_PATH=0 npx playwright install
    startCommand: node recon_playwright_agent.js
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: "0"
    plan: free