{ pkgs }: {
  deps = [
    pkgs.python311
    pkgs.portaudio
    pkgs.ffmpeg-full
    pkgs.SDL2
    pkgs.SDL2_image
    pkgs.SDL2_mixer
    pkgs.SDL2_ttf
    pkgs.cairo
    pkgs.fontconfig
    pkgs.freetype
    pkgs.geckodriver
    pkgs.ghostscript
    pkgs.glibcLocales
    pkgs.gobject-introspection
    pkgs.gtk3
    pkgs.libGL
    pkgs.libGLU
    pkgs.libjpeg
    pkgs.libpng
    pkgs.libxcrypt
    pkgs.pkg-config
    pkgs.portmidi
    pkgs.qhull
    pkgs.tcl
    pkgs.tk
  ];
}