# === FILE: whisper_to_mission.py ===

# 🎤 Whisper Mission – Converts voice transcriptions into .py mission files

import os
from ghost_relay_bot import inject_task

def process_voice_command(transcript):
    filename = "voice_cmd_" + transcript.replace(" ", "_") + ".py"
    code = f"# Mission generated by voice\nprint('[Voice] 🔊 {transcript}')\n"
    inject_task(filename, code, source="Whisper")

# Example use:
if __name__ == "__main__":
    process_voice_command("run diagnostics on system")