Sure, I can provide a simple example of a Python code that implements and tests a basic trading strategy. This is a Moving Average Crossover strategy using pandas library.

```python
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pandas_datareader import data as web

# Define the instruments to download. We would like to see Apple, Microsoft and others.
companies_dict = {
    'Apple': 'AAPL',
    'Microsoft': 'MSFT',
    'Amazon': 'AMZN',
    'Google': 'GOOG',
}

companies = sorted(companies_dict.items(), key=lambda x: x[1])

# Define which online source to use
data_source = 'yahoo'

# Define the start and end dates
start_date = '2015-01-01'
end_date = '2020-12-31'

# Use pandas_datareader.data.DataReader to load the desired data
panel_data = web.DataReader(list(companies_dict.values()), data_source, start_date, end_date)

# Calculate the short-window simple moving average
short_rolling = panel_data.rolling(window=20).mean()

# Calculate the long-window simple moving average
long_rolling = panel_data.rolling(window=100).mean()

# Create signals
signals = pd.DataFrame(index=panel_data.index)
signals['signal'] = 0.0

# Create short simple moving average over the short window
signals['short_mavg'] = panel_data['Close'].rolling(window=20, min_periods=1, center=False).mean()

# Create long simple moving average over the long window
signals['long_mavg'] = panel_data['Close'].rolling(window=100, min_periods=1, center=False).mean()

# Create signals
signals['signal'][short_rolling['Close'] > long_rolling['Close']] = 1.0

# Generate trading orders
signals['positions'] = signals['signal'].diff()

# Print `signals`
print(signals)
```

This code will print out a DataFrame that includes the short and long moving averages, as well as the signals and positions generated by the strategy. 

Please note that this is a very basic trading strategy and in real-world scenarios, trading strategies can get very complex. Also, this code does not include transaction costs. 

You would need to install the `pandas_datareader` library to fetch the data from Yahoo Finance. You can install it via pip:

```bash
pip install pandas_datareader
```

Remember to replace 'AAPL', 'MSFT', 'AMZN', 'GOOG' with the actual stock tickers you are interested in.