from ghost_env import INFURA_KEY, VAULT_ADDRESS
Sure, I can help you to write a simple Python code for a basic trading strategy. We will use the Moving Average Crossover Strategy which is a popular strategy in algorithmic trading.

Please note that this is a basic example and real trading involves many other factors which are not considered in this code. Also, you need to install `pandas`, `yfinance`, `matplotlib` and `numpy` libraries to run this code.

```python
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
import numpy as np

# Define the ticker symbol
tickerSymbol = 'AAPL'

# Get data on this ticker
tickerData = yf.Ticker(tickerSymbol)

# Get the historical prices for this ticker
tickerDf = tickerData.history(period='1d', start='2010-1-1', end='2020-1-25')

# Use close price for our calculations
close = tickerDf['Close']

# Calculate the short-term exponential moving average (EMA)
ShortEMA = close.ewm(span=12, adjust=False).mean()

# Calculate the long-term exponential moving average (EMA)
LongEMA = close.ewm(span=26, adjust=False).mean()

# Calculate the Moving Average Convergence/Divergence (MACD)
MACD = ShortEMA - LongEMA

# Calculate the signal line
signal = MACD.ewm(span=9, adjust=False).mean()

# Create a new column in the dataframe to hold the trading strategy signals
tickerDf['Buy_Signal_Flag'] = np.where(MACD > signal, 1, 0) # 1 means buy, 0 means sell

# Plot the close price and the buy signals
plt.figure(figsize=(12,5))
plt.plot(tickerDf.index, close, label='Close Price', color='blue')
plt.plot(ShortEMA.index, ShortEMA, label='Short/Fast EMA', color='red')
plt.plot(LongEMA.index, LongEMA, label='Long/Slow EMA', color='green')
plt.scatter(tickerDf.index, tickerDf['Buy_Signal_Flag'], color='red',marker='^', alpha=1)
plt.scatter(tickerDf.index, tickerDf['Sell_Signal_Flag'], color='green',marker='v', alpha=1)
plt.title('Close Price Buy & Sell Signals')
plt.xlabel('Date',fontsize=15)
plt.ylabel('Close Price USD ($)',fontsize=15)
plt.legend(loc='upper left')
plt.show()
```

This code will plot the close price of the stock along with the buy and sell signals generated by the Moving Average Crossover Strategy. The red markers on the plot represent the buy signals and the green markers represent the sell signals.