The Relative Strength Index (RSI) is a momentum oscillator that measures the speed and change of price movements. It is used to identify overbought or oversold conditions in a market. Here is a simple Python code that uses the `pandas` library to calculate the RSI and generate a trading strategy.

```python
import pandas as pd
import numpy as np

def calculate_rsi(data, window):
    delta = data.diff()
    up, down = delta.copy(), delta.copy()
    up[up < 0] = 0
    down[down > 0] = 0

    average_gain = up.rolling(window).mean()
    average_loss = abs(down.rolling(window).mean())

    rs = average_gain / average_loss
    rsi = 100 - (100 / (1 + rs))
    return rsi

def generate_rsi_strategy(data, window=14):
    # Calculate RSI
    rsi = calculate_rsi(data, window)
    data['RSI'] = rsi

    # Create signals
    data['Buy_Signal'] = np.where((data['RSI'] < 30), 1, 0)  # oversold condition
    data['Sell_Signal'] = np.where((data['RSI'] > 70), -1, 0)  # overbought condition

    # Generate strategy
    data['Strategy'] = data['Buy_Signal'] + data['Sell_Signal']

    return data

# Assume 'df' is a DataFrame with 'Close' prices
df = pd.DataFrame({'Close': [1,2,3,4,5,4,3,2,1,2,3,4,5,4,3,2,1,2,3,4,5]})
df = generate_rsi_strategy(df['Close'])
print(df)
```

In this code, the `calculate_rsi` function calculates the RSI for the given data over a specified window. The `generate_rsi_strategy` function then uses this RSI to generate trading signals: a buy signal when the RSI is below 30 (indicating an oversold condition) and a sell signal when the RSI is above 70 (indicating an overbought condition). The strategy is then generated by adding these buy and sell signals. 

Please replace the 'df' DataFrame with your actual data.